
services:
  app:
    image: "mcr.microsoft.com/devcontainers/go:1-1.22-bookworm"
    volumes:
      - ..:/workspace:cached
    ports:
      - "8090:8090"
    command: sleep infinity
 


  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_URI: ${MONGODB_URL}
    ports:
      - "27017:27017"
    volumes:
      - practice-mongo-db:/data/db 
      - practice-mongo-config:/data/configdb

volumes:
  practice-mongo-db:
  practice-mongo-config:
